import { NextResponse } from 'next/server';
import { query } from '@/lib/db';
import { v4 as uuidv4 } from 'uuid';
import { generateProjectPDF } from '@/lib/pdf';
import { sendQuotationEmail } from '@/lib/email';

export async function GET() {
  try {
    const projects = await query<any[]>('SELECT * FROM projects ORDER BY created_at DESC');
    
    // We need to fetch products and client details for each project to match the frontend shape
    const fullProjects = await Promise.all(projects.map(async (p) => {
      const clients = await query<any[]>('SELECT * FROM clients WHERE id = ?', [p.client_id]);
      const products = await query<any[]>('SELECT * FROM project_products WHERE project_id = ?', [p.id]);
      
      return {
        id: p.id,
        projectName: p.project_name,
        projectDate: p.project_date,
        status: p.status,
        totalAmount: p.total_amount,
        createdAt: p.created_at,
        client: clients[0] ? {
          id: clients[0].id,
          name: clients[0].name,
          companyName: clients[0].company_name,
          email: clients[0].email,
          phone: clients[0].phone,
          altPhone: clients[0].alt_phone,
          gstNumber: clients[0].gst_number,
          address: clients[0].address,
          totalProjects: clients[0].total_projects
        } : null,
        products: products.map(prod => ({
          id: prod.id,
          type: prod.type,
          width: prod.width,
          height: prod.height,
          quantity: prod.quantity,
          glassType: prod.glass_type,
          frameColor: prod.frame_color,
          hardware: prod.hardware,
          remarks: prod.remarks,
          unitPrice: prod.unit_price
        }))
      };
    }));

    return NextResponse.json(fullProjects);
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: 'Failed to fetch projects' }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const data = await req.json();
    const id = data.id || `PRJ-${uuidv4()}`;
    const clientId = data.client?.id;
    
    await query(
      `INSERT INTO projects (id, project_name, project_date, client_id, status, total_amount) 
       VALUES (?, ?, ?, ?, ?, ?)`,
      [
        id, 
        data.projectName || '', 
        data.projectDate || null, 
        clientId || null, 
        data.status || 'Pending', 
        data.totalAmount || 0
      ]
    );

    if (data.products && Array.isArray(data.products)) {
      for (const prod of data.products) {
        await query(
          `INSERT INTO project_products (project_id, type, width, height, quantity, glass_type, frame_color, hardware, remarks, unit_price)
           VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
          [
            id, prod.type, prod.width, prod.height, prod.quantity,
            prod.glassType, prod.frameColor, prod.hardware, prod.remarks, prod.unitPrice
          ]
        );
      }
    }
    
    // Attempt to generate PDF and send email asynchronously
    if (data.client?.email) {
      try {
        const settingsRes = await query<any[]>('SELECT * FROM settings LIMIT 1');
        const settings = settingsRes[0] || {};
        
        let pdfBuffer;
        if (data.pdfBase64) {
          // Use the exact UI representation generated by html2pdf on the client
          // jsPDF datauristring might contain filename, so safely split by comma
          const base64Data = data.pdfBase64.includes(',') ? data.pdfBase64.split(',')[1] : data.pdfBase64;
          pdfBuffer = Buffer.from(base64Data, 'base64');
        } else {
          // Fallback to basic pdfkit generation if frontend didn't provide it
          pdfBuffer = await generateProjectPDF(data, settings);
        }

        await sendQuotationEmail(data.client.email, data.client.name || 'Valued Client', pdfBuffer, data.projectName || id);
        console.log(`Quotation emailed to ${data.client.email}`);
      } catch (emailErr) {
        console.error('Failed to generate or send PDF email:', emailErr);
      }
    }

    return NextResponse.json({ message: 'Project created', id }, { status: 201 });
  } catch (error) {
    console.error(error);
    return NextResponse.json({ error: 'Failed to create project' }, { status: 500 });
  }
}
