import PDFDocument from 'pdfkit';
import { ValidatedSubmissionData } from './validation';

export async function generateSubmissionPDF(data: ValidatedSubmissionData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc.fontSize(20).text('Company Name', { align: 'center' });
      doc.moveDown();
      doc.fontSize(16).text('Submission Report', { align: 'center' });
      doc.moveDown();
      doc.fontSize(10).text(`Date: ${new Date().toLocaleString()}`, { align: 'right' });
      doc.moveDown(2);

      // Table Header (Simple text-based table)
      const startX = 50;
      let startY = doc.y;

      doc.rect(startX, startY, 500, 20).fillAndStroke('#f0f0f0', '#cccccc');
      doc.fillColor('#000000').fontSize(12).text('Field', startX + 10, startY + 5);
      doc.text('Details', startX + 150, startY + 5);
      doc.moveDown(1);

      // Table Data
      const fields = [
        { label: 'Name:', value: data.name },
        { label: 'Email:', value: data.email },
        { label: 'Phone:', value: data.phone },
        { label: 'Company:', value: data.company || 'N/A' },
        { label: 'Message:', value: data.message }
      ];

      fields.forEach((field) => {
        let currentY = doc.y;
        if (currentY > 700) {
          doc.addPage();
          currentY = doc.y;
        }
        
        doc.fontSize(10).text(field.label, startX + 10, currentY);
        doc.text(field.value, startX + 150, currentY, { width: 340 });
        
        doc.moveDown(0.5);
        doc.moveTo(startX, doc.y).lineTo(startX + 500, doc.y).stroke('#eeeeee');
        doc.moveDown(0.5);
      });

      // Footer
      const pages = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
      for (let i = 0; i < pages; i++) {
        doc.switchToPage(i);
        doc.fontSize(10).fillColor('gray').text(
          `Page ${i + 1} of ${pages} | Auto-generated by Next.js Backend Workflow`,
          50,
          720,
          { align: 'center' }
        );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export async function generateProjectPDF(project: any, settings: any): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const buffers: Buffer[] = [];

      doc.on('data', buffers.push.bind(buffers));
      doc.on('end', () => {
        const pdfData = Buffer.concat(buffers);
        resolve(pdfData);
      });

      // Header
      doc.fontSize(20).text(settings?.name || 'ADL UPVC Doors & Windows', { align: 'center' });
      doc.moveDown(0.5);
      doc.fontSize(12).fillColor('gray').text('Official Quotation Document', { align: 'center' });
      doc.moveDown(2);

      // Info Section
      const startX = 50;
      doc.fillColor('black').fontSize(10);
      
      doc.text('Client Details:', startX, doc.y, { underline: true });
      doc.moveDown(0.5);
      doc.text(`Name: ${project.client?.name || 'N/A'}`);
      doc.text(`Email: ${project.client?.email || 'N/A'}`);
      doc.text(`Phone: ${project.client?.phone || 'N/A'}`);
      doc.text(`Address: ${project.client?.address || 'N/A'}`);
      
      doc.moveUp(5);
      
      const rightX = 350;
      doc.text('Project Details:', rightX, doc.y, { underline: true });
      doc.moveDown(0.5);
      doc.text(`Project Name: ${project.projectName}`);
      doc.text(`Date: ${project.projectDate}`);
      doc.text(`Quotation ID: ${project.id}`);

      doc.moveDown(3);

      // Table Header
      let startY = doc.y;
      doc.rect(startX, startY, 500, 20).fillAndStroke('#185FA4', '#185FA4');
      doc.fillColor('white').fontSize(10).font('Helvetica-Bold');
      doc.text('Item Type', startX + 10, startY + 5, { width: 150 });
      doc.text('Dimensions', startX + 160, startY + 5, { width: 100 });
      doc.text('Qty', startX + 270, startY + 5, { width: 50 });
      doc.text('Unit Price', startX + 330, startY + 5, { width: 80, align: 'right' });
      doc.text('Total', startX + 420, startY + 5, { width: 70, align: 'right' });
      
      doc.moveDown(1);

      // Table Rows
      doc.font('Helvetica').fillColor('black');
      let subtotal = 0;
      
      if (project.products && Array.isArray(project.products)) {
        project.products.forEach((p: any, index: number) => {
          let currentY = doc.y;
          if (currentY > 700) {
            doc.addPage();
            currentY = doc.y;
          }
          
          const rowTotal = (p.unitPrice || 0) * p.quantity;
          subtotal += rowTotal;
          
          // Background alternating
          if (index % 2 === 0) {
            doc.rect(startX, currentY - 5, 500, 20).fill('#f9fafb');
            doc.fillColor('black');
          }
          
          doc.text(p.type || 'Window', startX + 10, currentY, { width: 150 });
          doc.text(`${p.width} x ${p.height}`, startX + 160, currentY, { width: 100 });
          doc.text(p.quantity?.toString() || '1', startX + 270, currentY, { width: 50 });
          doc.text(`Rs. ${p.unitPrice || 0}`, startX + 330, currentY, { width: 80, align: 'right' });
          doc.text(`Rs. ${rowTotal}`, startX + 420, currentY, { width: 70, align: 'right' });
          
          doc.moveDown(1);
        });
      }

      // Totals
      doc.moveDown(1);
      const tax = subtotal * 0.08;
      const grandTotal = subtotal + tax;
      
      const summaryX = 350;
      let summaryY = doc.y;
      
      doc.rect(summaryX - 10, summaryY - 5, 170, 70).fill('#f8fafc');
      doc.fillColor('black');
      
      doc.text('Subtotal:', summaryX, summaryY);
      doc.text(`Rs. ${subtotal}`, summaryX + 70, summaryY, { align: 'right', width: 80 });
      
      doc.text('Tax (8%):', summaryX, summaryY + 15);
      doc.text(`Rs. ${tax.toFixed(2)}`, summaryX + 70, summaryY + 15, { align: 'right', width: 80 });
      
      doc.font('Helvetica-Bold');
      doc.text('Total:', summaryX, summaryY + 35);
      doc.text(`Rs. ${grandTotal.toFixed(2)}`, summaryX + 70, summaryY + 35, { align: 'right', width: 80 });

      // Footer
      const pages = doc.bufferedPageRange ? doc.bufferedPageRange().count : 1;
      for (let i = 0; i < pages; i++) {
        doc.switchToPage(i);
        doc.fontSize(8).fillColor('gray').font('Helvetica').text(
          `Generated on ${new Date().toLocaleDateString()} | Page ${i + 1} of ${pages}`,
          50,
          720,
          { align: 'center' }
        );
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}
